improved init.sh.in - it is now possible to specify various paths (like SSL directory, Mnesia directory) in Makefile.template so that having multiple parallell Yxa versions installed is possible.
git-svn-id: svn://anonsvn.it.su.se/yxa/trunk@295 e454d3dc-12ff-0310-9b8b-94264392205f

diff --git a/init.sh.in b/init.sh.in
--- a/init.sh.in
+++ b/init.sh.in
@@ -1,3 +1,94 @@
 #!/bin/sh
-. /mpkg/modules/current/init/sh
-module add erlang
+#
+# Script created from Yxa init.sh.in
+#
+
+PROGRAMNAME="@PROGRAMNAME@"
+CONFIGDIR="@CONFIGDIR@"
+SSLCERTDIR="@SSLCERTDIR@"
+MNESIADIR="@MNESIADIR@"
+BUILDDIR="@BUILDDIR@"
+DETACH="-detached"
+
+HOSTNAME=`hostname`
+MYNAME=`basename $0`
+
+# Set up environment to include path to Erlang
+case $HOSTNAME in
+    *.kth.se)
+	. /mpkg/modules/current/init/sh
+	module add erlang
+	;;
+    *.su.se)
+	. /afs/su.se/common/etc/smodule/sh.init
+	module add erlang
+	;;
+    *)
+	PATH="$PATH:/usr/local/bin"
+	export PATH
+	;;
+esac
+
+# Calculate Erlang arguments
+if [ "x$CONFIGDIR" = "x" ]
+then
+	CONFIGPATH="$PROGRAMNAME"
+else
+	CONFIGPATH="$CONFIGDIR/$PROGRAMNAME"
+fi
+
+if [ "x$BUILDDIR" = "x" ]
+then
+	SEARCHPATHPARAMETERS=""
+else
+	SEARCHPATHPARAMETERS="-pz $BUILDDIR"
+fi
+
+if [ "x$SSLCERTDIR" = "x" ]
+then
+	SSLCERTFILE="ssl/cert.comb"
+else
+	SSLCERTFILE="$SSLCERTDIR/cert.comb"
+fi
+
+if [ "x$MNESIADIR" = "x" ]
+then
+	MNESIAPARAMETERS=""
+else
+	MNESIAPARAMETERS="-mnesia dir '"$MNESIADIR"'"
+fi
+
+if [ "x$1" = "x-d" ]
+then
+	DETACH=""
+fi
+
+if [ "x$MYNAME" = "xbootstrap.sh" ]
+then
+	if [ "x$ADMINPW" = "x" ]
+	then
+		echo "You are not following the instructions in README!"
+		echo ""
+		echo "You need to set the environment variable ADMINPW"
+		echo "before executing $0. Like this :"
+		echo ""
+		echo "  $ ADMINPW=foo $0"
+		echo ""
+		exit 1
+	fi
+
+	# yes, the name should be incomingproxy
+	erl $SEARCHPATHPARAMETERS -name incomingproxy -noshell $MNESIAPARAMETERS \
+		-run bootstrap start "$ADMINPW" -run init stop
+else
+	if [ ! -r "${CONFIGPATH}.config" ]
+	then
+		echo "$0: Configuration file ${CONFIGPATH}.config not found or not readable"
+		exit 1
+	fi
+
+	erl -boot $PROGRAMNAME $SEARCHPATHPARAMETERS -name $PROGRAMNAME -config $CONFIGPATH \
+		-proto_dist inet_ssl -ssl_dist_opt client_certfile $SSLCERTFILE \
+		-ssl_dist_opt server_certfile $SSLCERTFILE -ssl_dist_opt verify 2 \
+		$MNESIAPARAMETERS $DETACH
+fi
