Automatically create mnesia directory if it does not exist, for all applications except 'incomingproxy'. Suggested by Mikael Magnusson.
git-svn-id: svn://anonsvn.it.su.se/yxa/trunk@1432 e454d3dc-12ff-0310-9b8b-94264392205f

diff --git a/scripts/init.sh.in b/scripts/init.sh.in
--- a/scripts/init.sh.in
+++ b/scripts/init.sh.in
@@ -242,9 +242,22 @@ fi
 if [ "x$mnesiadir" = "x" ]; then
     mnesiaparameters=""
 else
-    if [ ! -d "$mnesiadir" -a $is_bootstrap -ne 1 ]; then
-	echo "$0: Mnesia directory '$mnesiadir' does not exist!"
-	exit 1
+    if [ ! -d "$mnesiadir" ]; then
+	if [ $is_bootstrap -ne 1 -a "x$name" = "xincomingproxy" ]; then
+	    echo "$0: Mnesia directory '$mnesiadir' does not exist!"
+	    echo ""
+	    echo "You should probably bootstrap YXA before starting the 'incomingproxy' application,"
+	    echo "see the README file. If 'incomingproxy' is not your database server node,"
+	    echo "just create the directory manually."
+	    echo ""
+	    exit 1
+	else
+	    mkdir "$mnesiadir"
+	    if [ ! -d "$mnesiadir" ]; then
+		echo "$0: Could not create Mnesia directory '$mnesiadir'"
+		exit 1
+	    fi
+	fi
     fi
     mnesiaparameters="-mnesia dir '"$mnesiadir"'"
 fi
